-- Songs: the registry of bundled songs and their track->patch maps.
-- The map is the "instrumentation" step the Playdate engine leaves to
-- us: keys are sequence track indices (check the console print from
-- MidiPlayer.load for what a new file parses to), values are Patches
-- names. Unmapped tracks get a heuristic guess.

Songs = {
    {
        name = "Demo Groove",
        path = "songs/demo.mid",
        -- generated by tools/mkmidi.py. The loader indexes by file
        -- track order (tempo track eats index 1), NOT by MIDI channel:
        -- smoke-verified 2026-07-04. The heuristic guessed all four
        -- correctly with an empty map; pinned anyway for stability.
        map = { [2] = "lead", [3] = "pad", [4] = "bass", [5] = "drums" },
        volume = {},
    },
    -- real-world test files from github.com/ldrolez/free-midi-chords
    -- (MIT; see songs/LICENSE-free-midi-chords.txt). Format-1, one
    -- chord track each; maps left empty to exercise the heuristic.
    {
        name = "F: IV vi iii I (Nostalgic)",
        path = "songs/prog-major.mid",
        map = {},
    },
    {
        name = "Am: i ii v i (Mysterious)",
        path = "songs/prog-minor.mid",
        map = {},
    },
    {
        name = "A: bIIIM ii bIIM I (Modal)",
        path = "songs/prog-modal.mid",
        map = {},
    },
}
